blank_issues_enabled: true
contact_links:
  - name: General discussion
    url: https://github.com/blackteahamburger/mu/discussions/
    about: You can talk about anything else in the Discussions section.
  - name: Tutorials & Guides
    url: https://codewith.mu
    about: Have you checked the Mu website for documentation first?
